### YamlMime:FAQ
metadata:
  title: Frequently asked questions | Power Pages security
  description: Frequently asked questions about security in Power Pages.
  author: sandhangitmsft  
  ms.topic: faq
  ms.custom: 
  ms.subservice: 
  ms.date: 08/24/2023
  ms.author: sandhan
  ms.reviewer: kkendrick
  contributors:
    - ProfessorKendrick

title: Power Pages security FAQs 

sections: 
  - name: General
    questions:
      - question: |
          How does Power Pages help to protect against clickjacking? 
        answer: |
          [Clickjacking](https://owasp.org/www-community/attacks/Clickjacking) uses embedded iframes, among other components, to hijack a user's interactions with a web page.  
          Power Pages provides HTTP/X-Frame-Options site stings with default SAMEORIGIN to provide protection against clickjacking attack.<br />   
          More information: [Set up HTTP headers in Power Pages](../configure/cors-support.md)
      
      - question: |
          Does Power Pages support Content Security Policy? 
        answer: |
          Power Pages supports Content security policy (CSP). Extensive testing is recommended after enabling CSP on the websites.<br />
          More information: [Manage content security policy](manage-content-security-policy.md)

      - question: |
           Does Power Pages support HTTP Strict Transport Security Policy? 
        answer: |
          By default, Power Pages supports http to https redirects. If this is flagged, verify if request is getting blocked at App Service Level. 
          If it's not a success request (response code >= 400), it’s a false positive. 
      
      - question: |
          Why cookies without HTTPOnly/SameSite flag are being detected/reported by pen test tools? 
        answer: |
          Power Pages sets HTTPOnly/SameSite flag for every critical cookie. There are some noncritical cookies for which HTTPOnly/SameSite isn't set, these shouldn't be considered as vulnerability.<br />
          More information: [Cookies in Power Pages](../admin/cookies.md)
      
      - question: |
          My Pen test report is flagging End of Life/Obsolete Software – Bootstrap 3, what should I do about it? 
        answer: |
          There are no known vulnerabilities on Bootstrap 3, however, Power Pages now supports Bootstrap 5 (It's in preview), consider migrating to it. 
      
      - question: |
          What ciphers does Power Pages support? What's the roadmap of continuously moving towards stronger ciphers? 
        answer: |
          All Microsoft services and products are configured to use the approved cipher suites, in the exact order directed by the Microsoft Crypto Board. 
          For the full list and exact order, see the Power Platform documentation. 
          Information about deprecations of cipher suites is communicated through Power Platform's Important Changes documentation. 
      
      - question: |
          Why does Power Pages still support RSA-CBC ciphers (TLS_ECDHE_RSA_with AES_128_CBC_SHA256 (0xC027) and TLS_ECDHE_RSA_with_AES_256_CBC_SHA384 (0xC028)), which are considered weaker? 
        answer: |
          Microsoft weighs the relative risk and disruption to customer operations in choosing cipher suites to support. The RSA-CBC cipher suites haven't been broken yet. We've enabled them to ensure consistency across our services and products, and to support all customer configurations. However, they're at the bottom of the priority list.
          We'll deprecate these ciphers based on the Microsoft Crypto Board's continuous assessment. 
          More information: 

      - question: |
          How do Power Pages protect against Distributed Denial of Service (DDoS) attacks? 
        answer: |
          Power Pages is built on Microsoft Azure and uses Azure DDoS Protection to guard against DDoS attacks.
          Also enabling OOB/Third party AFD/WAF can add additional protection on the site.
          refer bellow docs for enabling OOB/Third party AFD/WAF - 
          OOB AFD/WAF - .microsoft.com/en-us/power-pages/security/configure-web-application-firewall 
          External CDN - Configure a site with Content Delivery Network | Microsoft Learn 

      - question: |
          My Pen test report is flagging vulnerability in CKEditor, how to mitigate it? 
        answer: |
          CKEditor will soon be replaced by RTE PCF control. Until then if you want to mitigate this issue CKEditor can be disabled by configuring site setting DisableCkEditorBundle = true. Once CKEditor is disabled it will be replaced by a text field. 

      - question: |
          How to protect my website against XSS attacks? 
        answer: |
          It is recommended to perform html encoding before rendering data from an untrusted source. Please refer for available encoding filters - https://learn.microsoft.com/en-us/power-pages/configure/liquid/liquid-filters#escape-filters 